"""alter date columns

Revision ID: 18a21eafeedd
Revises: 1ebe2c999c10
Create Date: 2023-01-12 16:24:37.858375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a21eafeedd'
down_revision = '1ebe2c999c10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
