"""create all tables

Revision ID: 67c96ba03ce3
Revises: 
Create Date: 2023-04-04 22:40:10.842145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c96ba03ce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('number_of_calls', sa.Integer(), nullable=True),
    sa.Column('stoploss_target', sa.Integer(), nullable=False),
    sa.Column('performance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_of_brokers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('equity_delivery', sa.Float(), nullable=True),
    sa.Column('equity_intraday', sa.Float(), nullable=True),
    sa.Column('transaction_chgs', sa.Float(), nullable=True),
    sa.Column('dp_chgs', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stt_delivery', sa.Float(), nullable=False),
    sa.Column('stt_intraday', sa.Float(), nullable=False),
    sa.Column('gst', sa.Float(), nullable=False),
    sa.Column('sebi_chgs', sa.Float(), nullable=False),
    sa.Column('stamp_duty_delivery', sa.Float(), nullable=False),
    sa.Column('stamp_duty_intraday', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('hash_password', sa.String(length=60), nullable=False),
    sa.Column('last_logged', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('trading_code', sa.String(length=45), nullable=False),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('equity_delivery', sa.Float(), nullable=False),
    sa.Column('equity_intraday', sa.Float(), nullable=False),
    sa.Column('transaction_chgs', sa.Float(), nullable=True),
    sa.Column('dp_chgs', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trading_code', sa.String(length=45), nullable=False),
    sa.Column('pay_in', sa.Integer(), nullable=False),
    sa.Column('debits', sa.Float(), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('pay_out', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('script', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('call', sa.String(length=10), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('time_frame', sa.Integer(), nullable=True),
    sa.Column('analyst', sa.String(length=50), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('call', sa.String(length=10), nullable=False),
    sa.Column('script', sa.String(length=45), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('brokerage_per_unit', sa.Float(), nullable=False),
    sa.Column('net_rate_per_unit', sa.Float(), nullable=False),
    sa.Column('net_total_before_levies', sa.Float(), nullable=False),
    sa.Column('transaction_chgs', sa.Float(), nullable=False),
    sa.Column('dp_chgs', sa.Float(), nullable=False),
    sa.Column('stt', sa.Float(), nullable=False),
    sa.Column('sebi_turnover_fees', sa.Float(), nullable=False),
    sa.Column('stamp_duty', sa.Float(), nullable=False),
    sa.Column('gst', sa.Float(), nullable=False),
    sa.Column('total_taxes', sa.Float(), nullable=False),
    sa.Column('net_total', sa.Float(), nullable=False),
    sa.Column('broker', sa.String(length=45), nullable=True),
    sa.Column('trading_code', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('research')
    op.drop_table('funds')
    op.drop_table('brokers')
    op.drop_table('users')
    op.drop_table('taxes')
    op.drop_table('list_of_brokers')
    op.drop_table('analysts')
    # ### end Alembic commands ###
