"""modify date column

Revision ID: 7969e876719e
Revises: 58a807f4c541
Create Date: 2023-01-12 21:16:47.275613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7969e876719e'
down_revision = '58a807f4c541'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_logged', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_logged')
    # ### end Alembic commands ###
