"""create all the table

Revision ID: 99453ee93e88
Revises: 37db6600e53c
Create Date: 2023-01-06 17:07:10.500981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99453ee93e88'
down_revision = '37db6600e53c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('number_of_calls', sa.Integer(), nullable=True),
    sa.Column('stoploss_target', sa.Integer(), nullable=False),
    sa.Column('performance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_of_brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('equity_delivery', sa.Float(), nullable=True),
    sa.Column('equity_intraday', sa.Float(), nullable=True),
    sa.Column('transaction_chgs', sa.Float(), nullable=True),
    sa.Column('dp_chgs', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stt_delivery', sa.Float(), nullable=False),
    sa.Column('stt_intraday', sa.Float(), nullable=False),
    sa.Column('gst', sa.Float(), nullable=False),
    sa.Column('sebi_chgs', sa.Float(), nullable=False),
    sa.Column('stamp_duty_delivery', sa.Float(), nullable=False),
    sa.Column('stamp_duty_intraday', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=10), nullable=True),
    sa.Column('script', sa.String(length=10), nullable=True),
    sa.Column('total_qty', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('trading_code', sa.String(length=45), nullable=False),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('equity_delivery', sa.Float(), nullable=False),
    sa.Column('equity_intraday', sa.Float(), nullable=False),
    sa.Column('transaction_chgs', sa.Float(), nullable=True),
    sa.Column('dp_chgs', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('script', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('call', sa.String(length=10), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('time_frame', sa.Numeric(), nullable=True),
    sa.Column('analyst', sa.String(length=50), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('call', sa.String(length=10), nullable=False),
    sa.Column('script', sa.String(length=45), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('brokerage_per_unit', sa.Float(), nullable=False),
    sa.Column('net_rate_per_unit', sa.Float(), nullable=False),
    sa.Column('net_total_before_levies', sa.Float(), nullable=False),
    sa.Column('transaction_chgs', sa.Float(), nullable=False),
    sa.Column('dp_chgs', sa.Float(), nullable=False),
    sa.Column('stt', sa.Float(), nullable=False),
    sa.Column('sebi_turnover_fees', sa.Float(), nullable=False),
    sa.Column('stamp_duty', sa.Float(), nullable=False),
    sa.Column('gst', sa.Float(), nullable=False),
    sa.Column('total_taxes', sa.Float(), nullable=False),
    sa.Column('net_total', sa.Float(), nullable=False),
    sa.Column('broker', sa.String(length=45), nullable=True),
    sa.Column('trading_code', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date')
    op.drop_table('transactions')
    op.drop_table('research')
    op.drop_table('brokers')
    op.drop_table('test')
    op.drop_table('taxes')
    op.drop_table('list_of_brokers')
    op.drop_table('analysts')
    # ### end Alembic commands ###
